import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { BOOK_INDEX_V19_ROWS } from '../src/drink-master-v1.9-book-index.mjs';
import { normalizeDrinkV19Key } from '../src/drink-master-v1.9-master.mjs';
import { DRINK_MASTER_EXPANSION_B01 } from '../src/drink-master-expansion-b01.mjs';
import { DRINK_MASTER_EXPANSION_B02 } from '../src/drink-master-expansion-b02.mjs';
import { DRINK_MASTER_EXPANSION_B03 } from '../src/drink-master-expansion-b03.mjs';
import { DRINK_MASTER_EXPANSION_B04 } from '../src/drink-master-expansion-b04.mjs';
import { DRINK_MASTER_EXPANSION_B05 } from '../src/drink-master-expansion-b05.mjs';
import { DRINK_MASTER_EXPANSION_B06 } from '../src/drink-master-expansion-b06.mjs';
import { DRINK_MASTER_EXPANSION_B07 } from '../src/drink-master-expansion-b07.mjs';
import { DRINK_MASTER_EXPANSION_B08 } from '../src/drink-master-expansion-b08.mjs';
import { DRINK_MASTER_EXPANSION_B09,DRINK_MASTER_EXPANSION_B09_ALIAS_ENTRIES,DRINK_MASTER_EXPANSION_B09_EVIDENCE_VERSION } from '../src/drink-master-expansion-b09.mjs';
const PRIOR=[DRINK_MASTER_EXPANSION_B01,DRINK_MASTER_EXPANSION_B02,DRINK_MASTER_EXPANSION_B03,DRINK_MASTER_EXPANSION_B04,DRINK_MASTER_EXPANSION_B05,DRINK_MASTER_EXPANSION_B06,DRINK_MASTER_EXPANSION_B07,DRINK_MASTER_EXPANSION_B08];
test('batch 09 adds three unique master keys',()=>{const occupied=new Set([...BOOK_INDEX_V19_ROWS.map(x=>normalizeDrinkV19Key(x.name)),...PRIOR.flatMap(b=>b.map(d=>normalizeDrinkV19Key(d.masterKey)))]);assert.equal(DRINK_MASTER_EXPANSION_B09.length,3);const keys=DRINK_MASTER_EXPANSION_B09.map(d=>normalizeDrinkV19Key(d.masterKey));assert.equal(new Set(keys).size,3);for(const key of keys)assert.equal(occupied.has(key),false,`duplicate key ${key}`);});
test('batch 09 aliases do not redirect an occupied name to another drink',()=>{const occupied=new Map();for(const {name} of BOOK_INDEX_V19_ROWS){const n=normalizeDrinkV19Key(name);occupied.set(n,n);}for(const batch of PRIOR)for(const d of batch){const target=normalizeDrinkV19Key(d.masterKey);for(const a of [d.masterKey,d.nameJa,...(d.aliases||[])])occupied.set(normalizeDrinkV19Key(a),target);}for(const d of DRINK_MASTER_EXPANSION_B09){const target=normalizeDrinkV19Key(d.masterKey);for(const a of [d.masterKey,d.nameJa,...(d.aliases||[])]){const n=normalizeDrinkV19Key(a);if(occupied.has(n))assert.equal(occupied.get(n),target,`alias collision ${n}`);}}const signatures=new Set();for(const [a,k] of DRINK_MASTER_EXPANSION_B09_ALIAS_ENTRIES){const sig=`${normalizeDrinkV19Key(a)}=>${normalizeDrinkV19Key(k)}`;assert.equal(signatures.has(sig),false,`duplicate alias entry ${sig}`);signatures.add(sig);}});
test('batch 09 has complete rarity recipe and evidence',()=>{for(const d of DRINK_MASTER_EXPANSION_B09){assert.equal(d.availability+d.rarity,100);assert.ok(d.confidence>=0.7&&d.confidence<=1);assert.ok(d.recipe?.ingredients?.length>=3&&d.recipe?.method);assert.ok(d.shortDescription&&d.orderHint&&d.imageQuery);assert.ok(d.evidence?.length>=3);assert.ok(d.evidence.some(x=>x.type==='international_professional_reference'));assert.ok(d.evidence.some(x=>x.type.startsWith('jp_')));for(const e of d.evidence)assert.match(e.url,/^https:\/\//);}assert.equal(DRINK_MASTER_EXPANSION_B09_EVIDENCE_VERSION,'jp-rarity-expansion-2026-09-08-b09');});
test('deployment entrypoint seeds batch 09 before delegating to v1.9',async()=>{const wrapper=await readFile(new URL('../src/worker-v1.9-expansions.mjs',import.meta.url),'utf8');const wrangler=await readFile(new URL('../wrangler.jsonc',import.meta.url),'utf8');assert.match(wrapper,/DRINK_MASTER_EXPANSION_B09/);assert.match(wrapper,/seedB09/);assert.match(wrapper,/baseWorker\.fetch/);assert.match(wrangler,/worker-v1\.9-expansions\.mjs/);});
